import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import MainHeader from "@/components/ui/layout/MainHeader";
import { Volkhov } from "next/font/google";
import TopAnnouncementBar from "@/components/ui/layout/TopAnnouncementBar";
import { CartProvider } from "@/context/CartContext";
import { Toaster } from "sonner";

const volkhov = Volkhov({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sans",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", volkhov.variable, geistMono.variable, "font-sans",)}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <TopAnnouncementBar />
          <MainHeader />
          {children}
          <Toaster position="bottom-right" richColors closeButton />
        </CartProvider>
      </body>
    </html>
  );
}
